services:
  app:
    image: hello-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - VITE_BACKEND_URL=/api
    ports:
      - 5173:5173
    container_name: hello-front-dev
  debug-helper:
    image: busybox
